### PR TITLE
Profile Branch changes and Unit Tests

### PR DESCRIPTION
**Pull request by mitchellmui17**
Pull request collaboration with @DD155 . 
Please give a summary of the changes made in this pull request in the comment box below:

Mitchell-

- Resolved and fixed the issue regarding the profile page not obtaining the logout feature for unique users.
- Fixed some issues regarding unit testing on firebase. The package.JSON for UnitTest folder was not understanding the database unit testing file. It has been corrected to become "test.js". 
- Updated tutorial.txt for those who need to run Firebase simulator suite.
- fixed private route for logging out. Now private routes are officially set up for specific components. These components can only be accessed if the user is currently logged in. An attempt to access this will result in a redirect to the login page.

### CODE REVIEW

**Comment by dxliang001** [comment]
Thanks for fixing the logout button and make change for the profile page with connection to the database, this look great

**Comment by DD155** [comment]
> 
> 
> Pull request collaboration with @DD155 . Please give a summary of the changes made in this pull request in the comment box below:
> 
> Mitchell-
> 
>     * Resolved and fixed the issue regarding the profile page not obtaining the logout feature for unique users.
> 
>     * Fixed some issues regarding unit testing on firebase. The package.JSON for UnitTest folder was not understanding the database unit testing file. It has been corrected to become "test.js".
> 
>     * Updated tutorial.txt for those who need to run Firebase simulator suite.
> 
>     * fixed private route for logging out. Now private routes are officially set up for specific components. These components can only be accessed if the user is currently logged in. An attempt to access this will result in a redirect to the login page.

Profile changes:
Added database connection so db so profile details will load dynamically now
Added proper ignores for functions and statements that use the database so Jest does not conflict with our emulator testing
Removed unused code/tests (db addition) and added unit tests

**Review by chunxianlin — COMMENTED** [review]
Clear and clean code. Just don't forget to import the font.

**Comment by mitchellmui17** [comment]
@chunxianlin I thought we were changing the font to something else?

**Comment by mitchellmui17** [comment]
I can fix the font in the next pr with the new nav bar implementation

**Review by chunxianlin — APPROVED** [review]
The font will be changed in the next pull request.

**Pull request merged**
