### PR TITLE
Dynamic navbar added

### PR DESCRIPTION
**Pull request by mitchellmui17**
I changed the styling for nav bar to match theme colors. I also fixed the security issue regarding unique users. Now, users must be logged in the see the profile and calendar page. Without login, the website will only display home / contact us/ login in the nav  bar. Let me know if you have any questions guys.

### CODE REVIEW

**Review by Primagon — CHANGES_REQUESTED** [review]
Hello, I reviewed through your pull request. There are some things to note for the pull request.
In App.js, can you add back: 
<Route path="/" exact>
            <LandingPage /> 
<Route> 
as another alternative to:
<Route path="/Home" exact> 
              <LandingPage />
</Route>
That way, when the application has no page to go to, there wouldn't be a blank page.

I liked the colors you changed for the navBar, it looks consistent with the theme of our logo and application.

Also, in NavBar.js, I see that in line 13 you called database differently from Profile.js. Thank you for enlightening me with a different way to call for the database. I will use this when implementing Course.js

**Comment by Primagon** [comment]
Sorry it seems parts of my comment for the change requested disappeared because of how github reads the code.
The missing parts were asking you to add a route with "/" as another alternative path to "/Home".  That way, when the application has no page to go to, it will default to our home page.

**Comment by mitchellmui17** [comment]
yeah i can do that real quick, Im going to  make a push now

**Review by Primagon — APPROVED** [review]
Thank you for the quick change. I see this a much better alternative than what I suggested. This way, there won't be two redirects to our homepage. Also, it'll also look nicer when running our application. We won't see '/Home' at the end of the link anymore while on the homepage.

**Pull request merged**
