### PR TITLE
Firebase Unittesting for Database, and Set up unit test for signup

### PR DESCRIPTION
**Pull request by mitchellmui17**
I added the firebase emulator implementation recently in a new directory. The use for this is to test the database locally and check if the function calls we make to the firebase api work properly. Let me know if you guys need a tutorial for setting this up.

Another thing I added was finally being able to set up the Unit testing for signup. The undefined issue we were getting was fixed by using the mock functionality. Just be sure to pass the firebase api key when you guys need to unit test. Still haven't found a fix for that issue yet. Let me know what you guys think could be improved or what else I could possibly test for SignUp .

### CODE REVIEW

**Comment by dxliang001** [comment]
great job for fixing it, I think it's too many file change at one time, try to limited it

**Comment by mitchellmui17** [comment]
Yeah, i didn't mean to add this many lines of code to the push. when implementing firebase emulator a lot of the node modules got changed in the process

**Review by dxliang001 — APPROVED** [review]
great job for fixing it, I think it's too many file change at one time, try to limited it

**Review by Primagon — CHANGES_REQUESTED** [review]
In the firebase.js file, please change back the apiKey so no one else but us can access the database as an admin.

**Review by Primagon — APPROVED** [review]
Thank you for the quick change. Since you explained on discord that all the file changes were because of the firestore emulator and node modules. They caused a huge influx of file changes and lines added because it was needed for the emulator to work. For the files I was able to review, they looked like it was all for setting up firebase emulator and node modules after all. The text file on setting up unit testing using firestore emulator were helpful. Hopefully, this is the last time someone commits this many file and line changes.

**Pull request merged**
