### PR TITLE
Coursesv1

### PR DESCRIPTION
**Pull request by Primagon**
This pull request allows the user to add courses to their account. It would automatically add the submission to their Firebase document when they click 'Add Course' on the modal with valid entries.

### CODE REVIEW

**Comment by Primagon** [comment]
I realized the branch is called Coursesv1 but we ended up needing to update Profile first before continuing on the Course Page.

**Comment by mitchellmui17** [comment]
Things worked on: 

- connecting the database to link to courses attributes on the profile page. 
- helped with the implementation of linking the add courses feature variables into the database.

**Review by DD155 — APPROVED** [review]
In Profile.js: pushContent() can be written with less repetition. Instead of calling push five separate times, you can simply do courseList.push(courseNameRef, courseIDRef, ..., ..., ...) in one line (maybe you don't need a function for this then). It also seems like it is not being called in the code.

I would also recommend moving your functions outside of the component so you can export them to unit test them easier.

**Review by mitchellmui17 — COMMENTED** [review]
Good work Kenneth on this implementation. This is good progress in terms of the next steps for the courses page. I propose that now that we have these courses showing up on profile page. OnClick for the courses we can store the info as props that way we can dynamically allocate the information stored in the database into the respective course page. 


Also another side note, you should make sure you remove the push content function. I don't believe we need this function anymore. Lines: 105-111


For future references, lets remember to fix the styling on the page. No point of having href underlined courses. this looks unprofessional but we can worry about that at a later date.

**Review by mitchellmui17 — APPROVED** [review]

**Pull request merged**
