### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by chunxianlin**

### CODE REVIEW

**Comment by MuradAle** [comment]
the landing page was updated, now its divided into two-part, better if it has video background

**Review by DD155 — COMMENTED** [review]
Most of the CSS files are fine as they have minor changes, but I noticed that in LandingPage.css, you can do the layers better. 

For example, layer2-right and layer2-left are practically identical, except the few pixel changes in right and width. You can make a general layer class and put in all the properties that are not changing like background-color, position, box-shadow. And then you can give each element this general layer class instead. When you need to make specific changes to the top/left/etc. you can make an ID and refer to that instead. 

CSS Classes are generally used for reusable properties, and this will cut down the number of lines you need for this. 

You can also use an ID for it instead of a class because it seems like you are only using the style once throughout the code.

**Review by DD155 — CHANGES_REQUESTED** [review]
In LandingPage.js, please change 'class' to 'className' in your divs. This might be an issue later since it is recommended to use className with React.

**Review by MuradAle — APPROVED** [review]
A new logo has been added, changes in CSS code were added to font, LandingPage, Login, Navbar, and SignUp.

**Review by DD155 — APPROVED** [review]
Classnames changed.

**Pull request merged**
